template-file-path: ./multi-os-template.json

parameters:
  VpcId: AWS::EC2::VPC::Id
  SubnetId: AWS::EC2::Subnet::Id
  KeyName: AWS::EC2::KeyPair::KeyName
  CustomHtml: "<h1>Hello Ubuntu Git Sync!</h1>"
  InstanceName: UbuntuServer
  SelectedRegion: us-east-1
  AvailabilityZone: us-east-1a
  InstanceType: t2.micro
  OS: Ubuntu

tags:
  Environment: Dev
  Owner: Souleymane
  OS: Ubuntu
